"""init

Revision ID: 2dad874df614
Revises: e1a690c1f706
Create Date: 2026-09-27 20:10:16.994033

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2dad874df614'
down_revision: str | None = 'e1a690c1f706'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
