"""add api_base to models

Revision ID: 6162d24bd93e
Revises: 7b7739ff6b5b
Create Date: 2026-09-23 22:22:23.303369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6162d24bd93e'
down_revision: Union[str, None] = '7b7739ff6b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('api_base', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'api_base')
    # ### end Alembic commands ###
