"""add huggingface provider type

Revision ID: f6007268877e
Revises: 2dad874df614
Create Date: 2026-09-27 21:10:43.514182

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f6007268877e'
down_revision: str | None = '2dad874df614'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
